name: Build and Zip Extension

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Upload zip as artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension-zip
          path: |
            LICENSE
            background.js
            icon_off.png
            icon_on.png
            loading.html
            manifest.json
            popup.html
            popup.js